//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra
    {
        public string id { get; set; }
        public System.DateTime fecha { get; set; }
        public int usuario { get; set; }
        public string producto { get; set; }
        public int cantidad { get; set; }
        public float precio { get; set; }
    }
}
