//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int usuario { get; set; }
        public string producto { get; set; }
        public int cantidad { get; set; }
        public float precio { get; set; }
    }
}
