//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class consecutivo
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public string consecutivo1 { get; set; }
        public string prefijo { get; set; }
        public int rango_inicial { get; set; }
        public Nullable<int> rango_final { get; set; }
        public int usuario { get; set; }
    }
}
