//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class musica
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<int> genero { get; set; }
        public string tipo_interpretacion { get; set; }
        public string idioma { get; set; }
        public string pais { get; set; }
        public string disquera { get; set; }
        public string disco { get; set; }
        public Nullable<int> year { get; set; }
        public string url_descarga { get; set; }
        public string url_previsualizacion { get; set; }
    }
}
