//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class musica
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> usuario { get; set; }
        public int genero { get; set; }
        public string duration { get; set; }
        public string autor { get; set; }
    
        public virtual genero_musica genero_musica { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
