//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametro
    {
        public int id { get; set; }
        public string previsualizacion { get; set; }
        public string almacenamiento { get; set; }
        public int tipo { get; set; }
        public int usuario { get; set; }
    }
}
