//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametro
    {
        public string preLib { get; set; }
        public string almLib { get; set; }
        public string prePel { get; set; }
        public string almPel { get; set; }
        public string preMus { get; set; }
        public string almMus { get; set; }
    }
}
